<?php

/**
 * @file
 * Behance Block module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Theme hook.
 */
function behance_block_theme($existing, $type, $theme, $path) {
  return [
    'behance_block' => [
      'variables' => [
        'projects' => [],
        'tags' => [],
        'new_tab' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function behance_block_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.behance_block') {
    $readme_file = file_exists(__DIR__ . '/README.md') ? __DIR__ . '/README.md' : __DIR__ . '/README.txt';
    if (!file_exists($readme_file)) {
      return NULL;
    }
    $text = file_get_contents($readme_file);
    if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
      $config = ['settings' => $settings];
      $filter = $filter_manager->createInstance('markdown', $config);
      return $filter->process($text, 'en');
    }
  }
  return NULL;
}
