<?php

/**
 * @file
 * Behance Block module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function behance_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.behance_block':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a block to display Behance projects.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function behance_block_theme($existing, $type, $theme, $path) {
  return [
    'behance_block' => [
      'variables' => [
        'projects' => [],
        'tags' => [],
        'new_tab' => NULL,
      ],
    ],
  ];
}
